// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using OpenWeather_Desafio.Data;

namespace OpenWeather_Desafio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("OpenWeather_Desafio.Data.Cidade", b =>
                {
                    b.Property<DateTime>("Id")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<double>("Temp")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<double>("TempMax")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.Property<double>("TempMin")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new DateTime(2021, 12, 22, 12, 31, 45, 11, DateTimeKind.Local).AddTicks(9655),
                            Nome = "Teste",
                            Temp = 0.0,
                            TempMax = 0.0,
                            TempMin = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
